## Session #1 Homework

In [1]:
import numpy as np
import pandas as pd

### Question 1
What's the version of NumPy that you installed? 

In [2]:
# Numpy version
np.__version__

'1.21.5'

### Getting the data 

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-07 15:12:42--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.1s    

2022-09-07 15:12:43 (12.7 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [4]:
df = pd.read_csv('./data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 2
How many records are in the dataset?

In [5]:
# Question 2
# How many records are in the dataset?
df.shape[0]

11914

### Question 3
Who are the most popular car manufacturers (top-3) according to the dataset?

In [6]:
# Question 3
# Who are the most popular car manufacturers (top-3) according to the dataset?
df['Make'].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### Question 4
What's the number of unique Audi car models in the dataset?

In [7]:
df.loc[df['Make'] == 'Audi', 'Model'].nunique()

34

### Question 5
How many columns in the dataset have missing values?

In [8]:
df.isnull().sum() 

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [9]:
print(f'{(df.isnull().sum() > 0 ).sum()} columns in the dataset have missing values' )

5 columns in the dataset have missing values


### Question 6

* Find the median value of "Engine Cylinders" column in the dataset.
* Next, calculate the most frequent value of the same "Engine Cylinders".
* Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
* Now, calculate the median value of "Engine Cylinders" once again.


In [10]:
# Find the median value of "Engine Cylinders" column in the dataset.
median = df['Engine Cylinders'].median()
median

6.0

In [11]:
# Next, calculate the most frequent value of the same "Engine Cylinders".
mode = df['Engine Cylinders'].mode()
mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [12]:
#  Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
df['Engine Cylinders_filled'] = df['Engine Cylinders'].fillna(mode)
 #df['Engine Cylinders_filled']

In [13]:
# Now, calculate the median value of "Engine Cylinders" once again.
df[['Engine Cylinders', 'Engine Cylinders_filled']].median()

Engine Cylinders           6.0
Engine Cylinders_filled    6.0
dtype: float64

### Question 7

* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it `X`.
* Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
* Invert `XTX`.
* Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
* Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
* What's the value of the first element of `w`?

In [14]:
# Select all the "Lotus" cars from the dataset.
only_lotus = df[df['Make'] == 'Lotus']
# Select only columns "Engine HP", "Engine Cylinders".
only_lotus = only_lotus[["Engine HP", "Engine Cylinders"]]
#Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
only_lotus = only_lotus.drop_duplicates().reset_index(drop=True)
only_lotus

Engine HP  Engine Cylinders
0      189.0               4.0
1      218.0               4.0
2      217.0               4.0
3      350.0               8.0
4      400.0               6.0
5      276.0               6.0
6      345.0               6.0
7      257.0               4.0
8      240.0               4.0

In [15]:
# Get the underlying NumPy array. Let's call it `X`.
X = only_lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [16]:
# Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
XTX = X.transpose().dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [17]:
# Invert `XTX`.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [18]:
# Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [19]:
# Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
w = (XTX_inv.dot(X.transpose())).dot(y)
w[0]

4.594944810094579